### ISSUE TITLE
如何使用ENeRF训练自己的数据集

### ISSUE THREAD

**Issue by 7tu** [zju3dv/ENeRF#11]
尊敬的前辈：
           您好！最近拜读了贵学校的文章ENeRF，其是一项伟大的工作，对我很有启发。在复现了您的部分工作后，我想尝试使用自己的数据集在ENeRF上运行，但是出现了一些问题。我想请问一下我是否有机会得到您处理从colmap SfM result转换到 ENeRF input的方法。

**Comment by haotongl** [comment]
Please refer to https://github.com/Fyusion/LLFF/blob/master/imgs2poses.py to generate data in LLFF format.
