### ISSUE TITLE
near_far插值范围限定

### ISSUE THREAD

**Issue by chky1997** [zju3dv/ENeRF#14]
您好，目前代码利用了拟合的单人SMPL模型6890各顶点得到了3Dbbox，用来限定cost volume插值的深度(near_far)，请问像project page里展示的多人情况和带背景的情况，是不用这个方法进行处理吗？

**Comment by haotongl** [comment]
Please refer to our supplementary material. In this complex scene, we layered the scene, established ENeRF separately, and used volume rendering to synthesize these layers. We used a large 3D bounding box composed of two people's SMPL points as the foreground layer, and the background layer was determined using the background point cloud. We recently released the ENeRF-Outdoor dataset, and we expect to release the relevant code before the Spring Festival.
————————————————————————————————————————————————————————————
请参考我们的补充材料，arixv version paper Figure 6。我们在这种复杂的场景下，对场景进行了分层，分别建立了ENeRF，并且使用Volume rendering将这些层合成起来。我们使用两个人的SMPL点组成的大的3D bbox作为前景层，使用背景点云确定了背景层。我们最近公开了ENeRF-Outdoor dataset，预计春节前可以把相关code也release掉。

**Comment by chky1997** [comment]
谢谢，期待！
