### ISSUE TITLE
The agreement file of the ENeRF-Outdoor dataset

### ISSUE THREAD

**Issue by kjzju** [zju3dv/ENeRF#16]
I want to request the ENeRF-Outdoor dataset, but I can't find the agreement file that you mentioned for requesting the dataset.

**Comment by haotongl** [comment]
Thanks for your attention! I have updated the agreement link for ENeRF-Outdoor dataset. https://zjueducn-my.sharepoint.com/:b:/g/personal/haotongl_zju_edu_cn/Ebgr5EgPgDZDl5sj3nwV_-wBng8EExEIpS541YgMsgH7cw?e=wLQCR0
