### ISSUE TITLE
Only 13 FPS?

### ISSUE THREAD

**Issue by yijie21** [zju3dv/ENeRF#18]
I rerun your algorithm on LLFF dataset of resolution 512*512, but only get about 13 FPS. How to achieve 25 FPS mentioned in your paper?

**Comment by haotongl** [comment]
Hi, thanks for your attention. 25 FPS is not the rendering speed for LLFF dataset.
The rendering FPS on LLFF should be about 10FPS@960x640. 
As the rendering speed is strictly related to the resolution, we did not measure the rendering speed for each data in Table 2. Table 2 reports the speed of rendering DTU@512x512 for all comparison methods.

**Comment by yijie21** [comment]
Thank you very much!
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Haotong ***@***.***>
            
        
      
      
        
         Date 
        
        
        2/6/2023 23:19
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [zju3dv/ENeRF] Only 13 FPS? (Issue #18)
        
      
    
  
  
Hi, thanks for your attention. 25 FPS is not the rendering speed for LLFF dataset.
The rendering FPS on LLFF should be about ***@***.***
As the rendering speed is strictly related to the resolution, we did not measure the rendering speed for each data in Table 2. Table 2 reports the speed of rendering ***@***.*** for all comparison methods.
