### ISSUE TITLE
AttributeError: frames

### ISSUE THREAD

**Issue by ds22058** [zju3dv/ENeRF#21]
Great work! I met a problem when I using the flower in llff dataset to run gui_human.py with parameters '--cfg_file configs/enerf/llff/flower.yaml'. 
The error is:
Traceback (most recent call last):
  File "D:\pycharm\ENeRF\gui_human.py", line 380, in <module>
    main()
  File "D:\pycharm\ENeRF\gui_human.py", line 231, in main
    rend = Renderer()  # prepare network and dataloader
  File "D:\pycharm\ENeRF\gui_human.py", line 50, in __init__
    self.frame_start = cfg.test_dataset.frames[0]
  File "D:\pycharm\ENeRF\lib\config\yacs.py", line 115, in __getattr__
    raise AttributeError(name)
AttributeError: frames
 It seems like it don't have a 'frame' in test_dataset
<img width="809" alt="image" src="https://user-images.githubusercontent.com/114089143/221122902-47755672-dfa8-4756-a0ed-189508300da8.png">
Could you please help me with this problem? Thanks in advance!

**Comment by haotongl** [comment]
Hello, thank you for your attention! The script gui_human.py is designed for dynamic scenes (ZJUMoCap). 
The variable "frames" represents the number of the selected frames for the dynamic scene.
