### ISSUE TITLE
Question about quantitative evaluation on pretrained model

### ISSUE THREAD

**Issue by Tiansong97** [zju3dv/ENeRF#24]
I used the provided generalization model to perform evaluation on DTU dataset as in readme, and got the psnr, ssim and  lpips values:
![image](https://user-images.githubusercontent.com/37653264/221639846-fc05edc2-cb1e-4d3e-8967-834f71bcf93f.png)

whereas in readme, the quantitative results should be
![image](https://user-images.githubusercontent.com/37653264/221640115-42cb0d69-df12-45f9-8baa-02ae393c691d.png)

I wonder why the quantitative evaluation results are different? And I want to know your evaluation results? Thanks

**Comment by haotongl** [comment]
Hi, this result is very strange, can you provide me with more details? For example, pytorch version, operating environment.

Besides that, I also doubt whether the pre-trained model is loaded normally. Can you make sure that this line of code runs successfully?
https://github.com/zju3dv/ENeRF/blob/38c1b9087833926de897847636016b73f889d22b/lib/utils/net_utils.py#L443

**Comment by Tiansong97** [comment]
Thanks for your reply.
Yes the pretrained model is loaded successfully. To check this problem, we set "strict=True" and get the same results.

We run the code on an ubuntu server and Nvidia 3090 GPU. Pytorch version is the same as in readme, and other packages that may have influence are show as following:
![image](https://user-images.githubusercontent.com/37653264/221860508-f359404d-b6e6-4ff8-8387-8e257f9c8a65.png)
![image](https://user-images.githubusercontent.com/37653264/221860835-14a1e51b-e699-4555-a193-a6eca4dba9f6.png)
![image](https://user-images.githubusercontent.com/37653264/221864433-4a728113-24bc-4233-9879-e8e58bf63e68.png)


All the evaluation outputs on DTU dataset are shown as following:
![企业微信截图_16775885222453](https://user-images.githubusercontent.com/37653264/221861059-046b680d-5cb3-4393-afe8-e578aef50436.png)

The rendered images seem to be reasonable:
Scan114_32_0.png
![scan114_32_0](https://user-images.githubusercontent.com/37653264/221861381-1f7e1a7e-a7ec-45e9-ad46-aaea83cc2093.png)
scan45_44_0.png
![scan45_44_0](https://user-images.githubusercontent.com/37653264/221861502-0c2d5513-25ce-477a-a27f-3d5e97e24e7d.png)

What's more, the evaluation results on nerf_llff_data (32 images for evaluation in total) and nerf_synthetic_data (32 images for evaluation in total) are also different from the psnr, ssim & lpips results that are shown on paper:
![image](https://user-images.githubusercontent.com/37653264/221863029-b437a452-333a-47b7-869c-ef4ffb568bf8.png)
![image](https://user-images.githubusercontent.com/37653264/221863285-30b93a71-e04b-43f1-8c6c-001f9fc1a856.png)
![image](https://user-images.githubusercontent.com/37653264/221863426-415a079d-409d-49eb-ae40-57fc48c978ab.png)

Also, the rendered images seem to be reasonable:
chair_32_0.png (same as the image shown on the supplementary materials)
![chair_32_0](https://user-images.githubusercontent.com/37653264/221864766-fcb1ee42-f26a-4b28-9788-3515ccd19631.png)
fortress_25_0.png
![fortress_25_0](https://user-images.githubusercontent.com/37653264/221865117-a29f43e5-c910-4df4-a34a-92b19547ef9b.png)


We are writing a paper and prepare to cite your paper and compare with yours results, so we want to check this problem. Thanks.

**Comment by haotongl** [comment]
While the model appears to perform well on the other two datasets, there may be an issue with the format of the DTU dataset when it comes to the artifacts. Based on the provided rendering images, which are clearly 512x640 in size, it is possible that the camera pose scale is incorrect. To confirm this, could you please review the content of $workspace/dtu/Cameras/train/00000000_cam.txt.

```extrinsic
0.970263 0.00747983 0.241939 -191.02
-0.0147429 0.999493 0.0282234 3.28832
-0.241605 -0.030951 0.969881 22.5401
0.0 0.0 0.0 1.0

intrinsic
361.54125 0.0 82.900625
0.0 360.3975 66.383875
0.0 0.0 1.0

425.0 2.5
```

**Comment by Tiansong97** [comment]
We follow the readme to download the dtu, llff, nerf dataset. The camera paramters are shown as follows. It seems that there is no difference to your data.
![image](https://user-images.githubusercontent.com/37653264/221875960-5c816e07-00d3-4f14-9975-eb92f17a97b8.png)

We download the code, pretrained model and dataset, then we run the rendering command directly after specifying the dataset path. We didn't modify the dataset or the code.

**Comment by haotongl** [comment]
I'm sorry, it's my fault. I must have introduced a bug during my later update. However, I need to go to bed now and don't have time to locate where the bug is. A quick but temporary solution is to run "git checkout 2d6b3b2" and then execute the evaluation command.

I will address the issue tomorrow and update it on the master branch.

**Comment by haotongl** [comment]
I have solved this bug.
