### ISSUE TITLE
Question about the dimension of Forward_feat and render_rays in network_composite.py

### ISSUE THREAD

**Issue by louhz** [zju3dv/ENeRF#25]
Hi, I am confused about the dimension in Forward_feat and render_rays functions: the B,S,C,H,W, which is different from the traditional 5D B C D H W.
I assume the B is batch size and C,H,W are color, height and width. But I am not sure about the meaning of S dimension.
Can you offer me some intuition for this dimension?

Thanks!

**Comment by haotongl** [comment]
Hi, C is the number of feature channels. S is the number of input views (images).

**Comment by louhz** [comment]
> Hi, C is the number of feature channels. S is the number of input views (images).

Thanks!
