### ISSUE TITLE
The vedio of the ZJU-Mocap

### ISSUE THREAD

**Issue by ds22058** [zju3dv/ENeRF#27]
Hi, I try to prepare my own Mocap dataset to run your code but the youtube link in https://chingswy.github.io/easymocap-public-doc/quickstart/capture_youtube.html is private or not exist. Could you please release the multiview vedio of your Mocap vedio so that I can have a try on preparing Mocap dataset. Thanks in advance!

**Comment by ds22058** [comment]
I have another question. Following the https://chingswy.github.io/easymocap-public-doc/quickstart/prepare_mocap.html I get
<img width="418" alt="image" src="https://user-images.githubusercontent.com/114089143/222077448-5fb7e5e6-6ca3-4fc2-b8ed-0c742bde7cd9.png">However in Core_view313,
<img width="606" alt="image" src="https://user-images.githubusercontent.com/114089143/222077713-d7131045-47d0-44fa-bf43-70a68fdfa542.png">
it has annots.npy, annots.json and files like new_vertices and so on. Without them I can't run the'gui_human.py'. How can I get them.

**Comment by ds22058** [comment]
Also, I wanna know how to make my own enerf_outdoor dataset

**Comment by haotongl** [comment]
> https://chingswy.github.io/easymocap-public-doc/quickstart/prepare_mocap.html

Hi, ENeRF use the dataset format of NeuralBody. Please use this script to convert a dataset of MoCap format to NeuralBody format.
https://chingswy.github.io/easymocap-public-doc/quickstart/tools.html

**Comment by haotongl** [comment]
> Also, I wanna know how to make my own enerf_outdoor dataset

To make your own ENeRF_Outdoor dataset, please capture the dynamic scene using the multiple synchronized cameras.
https://github.com/zju3dv/ENeRF/blob/master/docs/enerf_outdoor.md

To generate the 3D bbox (vhull/000000.npy), you can run some background matting methods to generate the mask and then use the mask to compute visual hull for the foreground.
e.g., https://github.com/PeterL1n/BackgroundMattingV2

**Comment by haotongl** [comment]
> Hi, I try to prepare my own Mocap dataset to run your code but the youtube link in https://chingswy.github.io/easymocap-public-doc/quickstart/capture_youtube.html is private or not exist. Could you please release the multiview vedio of your Mocap vedio so that I can have a try on preparing Mocap dataset. Thanks in advance!

I am afraid that you should open an issue in EasyMocap repo to remind Dr. Shuai (https://github.com/chingswy) for the expired link.  Besides, I think it would take a lot of effort to get ENeRF to work on Internet Videos.

**Comment by CHDTevior** [comment]
May I ask how to obtain the annots.json and the new annots.npy? I want to finetune the model using my own data set similar to zju-mocap, but I found that the annots.npy file format of the two is different, which makes it unreadable. How do I get these files to work with?
