### ISSUE TITLE
About the dataloader codes for the Real Forward-facing and NeRF Synthetic datasets

### ISSUE THREAD

**Issue by happyday521** [zju3dv/ENeRF#3]
Hi, thanks for sharing your great work!
I want to know how to run your code on the Real Forward-facing and NeRF Synthetic datasets? It seems that you only release the dataloader code for DTU dataset? Can you release the dataloader codes for the Real Forward-facing and NeRF Synthetic datasets? 
Thanks very much!

**Comment by haotongl** [comment]
Thank you for your attention! We have the plan to release them as discussed in https://github.com/zju3dv/ENeRF/issues/2#issuecomment-1329993163
