### ISSUE TITLE
win_size exceeds image extent

### ISSUE THREAD

**Issue by luoshuiyue** [zju3dv/ENeRF#34]
![image](https://user-images.githubusercontent.com/25098355/230316891-21407aac-3887-4442-ac38-1b1837303b0f.png)

I want to ask how to solve this problem?

**Comment by luoshuiyue** [comment]
I ran it again without this problem.

**Comment by luoshuiyue** [comment]
The problem still occurs.

**Comment by haotongl** [comment]
Hello! Based on the image you provided, it appears that the height or width of the rendering image is smaller than 7. Can you please tell me what dataset you are using?

**Comment by luoshuiyue** [comment]
I used dtu dateset. I just followed the instructions provided, ran the command: python train_net.py --cfg_file configs/enerf/dtu_pretrain.yaml.

**Comment by haotongl** [comment]
Could you try the evaluation command to see if it can run normally? If it cannot run normally, can you print the shape of the input of the ssim function?

**Comment by haotongl** [comment]
I cannot reproduce your problem. Some possible reason maybe unmatched version of ssim function. Could you please try to use scikit-image==0.19.3?

**Comment by luoshuiyue** [comment]
Thank you very very much for your timely help! I tried version 0.19.3 and there is no error yet (program is stilling running). It seems to work. Thanks a lot!

**Comment by luoshuiyue** [comment]
> I cannot reproduce your problem. Some possible reason maybe unmatched version of ssim function. Could you please try to use scikit-image==0.19.3?
Thank you very much! This is the correct way to solve the problem.
