### ISSUE TITLE
Issues on evaluation

### ISSUE THREAD

**Issue by wangqiuwen1006** [zju3dv/ENeRF#36]
Hello! Thanks for sharing the code!

When I eval this model on LLFF dataset with test part (unseen scenes in theory), I found it perform much better in 'fortress' scene than other methods such as IBRNet, but other scenes have similar performances. So I would like to ask whether the 'latest.pth' you released is a model that has not been finetuned?

In addition, I want to know if I want to get an image whose image size does not fit the cost volume network (such as the original image size of the LLFF dataset), how should I do it？(matbe resize the size of the depth and the original image?)

I'm looking forward to your reply.

**Comment by haotongl** [comment]
We donot finetune the released model on fortress.
One possible reason is that the fortress is an object placed on a flat table, which is much simpler for our depth-based method.

We follow MVSNeRF to resize the LLFF images to 960x640.

**Comment by wangqiuwen1006** [comment]
Thanks for your answer! So what should I do if I want to render a 1008x756 image?

**Comment by haotongl** [comment]
One of simple solutions maybe we can resize the rendering resolution to 992x732 (1008//32*32), and resize the rendering result to 1008x756. I do not know if this meets your requirements.

**Comment by wangqiuwen1006** [comment]
Thank you!
