### ISSUE TITLE
No such file or directory: 'lib/visualizers/enerf.py'

### ISSUE THREAD

**Issue by JokerYan** [zju3dv/ENeRF#4]
Hi, thank you for your hard work. I have been trying to run the visualize module, but maybe it is not published yet? It says `No such file or directory: 'lib/visualizers/enerf.py'` or maybe I am doing something run.

I was running using the following command `python run.py --type visualize --cfg_file configs/enerf/llff_eval.yaml`

Looking forward to your release of the visualize, interactive rendering code and outdoor dataset!

Thank you

**Comment by haotongl** [comment]
python run.py --type evaluate --cfg_file configs/enerf/llff_eval.yaml save_result True save_tag llff

**Comment by JokerYan** [comment]
Thank you. However, the rendered images for the NeRF and LLFF dataset are not as good as the results presented in the paper or the video shown on the project page. May I ask how many cameras are used for the outdoor scene? (or maybe release the data if possible. Thx a lot)

**Comment by haotongl** [comment]
16-18 cameras on a 120 degree arc.
