### ISSUE TITLE
Super low GPU/CPU usage while training

### ISSUE THREAD

**Issue by anzisheng** [zju3dv/ENeRF#40]
I'm training with enerf-outdoor from scratch using the default configuration. The GPU/CPU usage is super low. What might be the cause?

![image](https://github.com/zju3dv/ENeRF/assets/16410690/2a847cc8-293c-4cae-a4b7-058a576ffd09)

**Comment by haotongl** [comment]
I noticed that the data section takes up half the time! Maybe it’s because the hard disk data reading speed is too slow.
