### ISSUE TITLE
Error in DTU Eval

### ISSUE THREAD

**Issue by ch1998** [zju3dv/ENeRF#41]
When using train_net.py to train, an error occurs when performing eval：
cv2.error:resize.cpp:4062:erroe:(-215:Assert failed) !ssize.empty() in function 'resize'

Locating errors 90-93 in dtu/enerf.py
tar_dpt = data_utils.read_pfm(scene_info['dpt_paths'][tar_view])[0].astype(np.float32)  tar_dpt0(128, 160)
tar_dpt = cv2.resize(tar_dpt, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_NEAREST)  tar_dpt1(64, 80)
tar_dpt = tar_dpt[44:556, 80:720]  tar_dpt2(20, 0)
tar_mask = (tar_dpt > 0.).astype(np.uint8)      tar_mask(20, 0)       

After spliting, tar_mask is empty
how to solve it？

**Comment by zhuangqirong** [comment]
> When using train_net.py to train, an error occurs when performing eval： cv2.error:resize.cpp:4062:erroe:(-215:Assert failed) !ssize.empty() in function 'resize'
> 
> Locating errors 90-93 in dtu/enerf.py tar_dpt = data_utils.read_pfm(scene_info['dpt_paths'][tar_view])[0].astype(np.float32) tar_dpt0(128, 160) tar_dpt = cv2.resize(tar_dpt, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_NEAREST) tar_dpt1(64, 80) tar_dpt = tar_dpt[44:556, 80:720] tar_dpt2(20, 0) tar_mask = (tar_dpt > 0.).astype(np.uint8) tar_mask(20, 0)
> 
> After spliting, tar_mask is empty how to solve it？
How do you solve this problem?

**Comment by zhuangqirong** [comment]
> When using train_net.py to train, an error occurs when performing eval： cv2.error:resize.cpp:4062:erroe:(-215:Assert failed) !ssize.empty() in function 'resize'
> 
> Locating errors 90-93 in dtu/enerf.py tar_dpt = data_utils.read_pfm(scene_info['dpt_paths'][tar_view])[0].astype(np.float32) tar_dpt0(128, 160) tar_dpt = cv2.resize(tar_dpt, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_NEAREST) tar_dpt1(64, 80) tar_dpt = tar_dpt[44:556, 80:720] tar_dpt2(20, 0) tar_mask = (tar_dpt > 0.).astype(np.uint8) tar_mask(20, 0)
> 
> After spliting, tar_mask is empty how to solve it？

How do you solve this problem?
