### ISSUE TITLE
Run Enerf on a self-made zju-mocap

### ISSUE THREAD

**Issue by CHDTevior** [zju3dv/ENeRF#43]
[I wanted to run Enerf on a dataset I made myself, which I got with EasyMocap and this link](https://github.com/zju3dv/neuralbody/tree/master/tools/custom)， Now I get file structure like this:
![image](https://github.com/zju3dv/ENeRF/assets/96759520/bc738d55-582f-4b56-a699-9e9b8bd85e46)
now I'm still missing files like new_vertices to run the visualization, how can I fix this?
![image](https://github.com/zju3dv/ENeRF/assets/96759520/7cda5eb2-0c05-48a5-92b3-706f85965a12)

**Comment by CHDTevior** [comment]
And I also want to ask how to get mask file.

**Comment by haotongl** [comment]
Hi, thanks for your attention! The mask can be predicted by backgound matting (if you have clean background images) or SCHP: https://github.com/GoGoDuck912/Self-Correction-Human-Parsing model.
The SCHP algorithm is supported by EasyMoCap.

**Comment by CHDTevior** [comment]
Thanks for your reply, I'll try it.

**Comment by CHDTevior** [comment]
If I directly copy the vertices file and name it new_vertices, I observed in previous questions that their functions seem to be the same, but the version generated by Easymocap is different
