### ISSUE TITLE
Question about config file

### ISSUE THREAD

**Issue by SuzyZhao0417** [zju3dv/ENeRF#49]
Hi, Thanks for your great work! During training, I find the code pass through the function name build_feature_volume twice, is this means coarse to fine? And I wondering how to change the parameters in cfg.enerf.cas_config, I cannot find the related parameters in lib.config. Looking forward to your reply！
Best wishes！

**Comment by haotongl** [comment]
Hi, thanks for your attention. Yes, it means coarse to fine.
I uploaded a config file without cascade cost volume. https://github.com/zju3dv/ENeRF/blob/master/configs/enerf/dtu_pretrain_nocascade.yaml  
I hope you find it useful.

**Comment by SuzyZhao0417** [comment]
> ###
> [Nov 1, 2023](#issuecomment-1788805571)

Thanks for your quick reply! And how can I change the H and W of feature map or you have fixed the parameters so we cannot change it?

**Comment by TT-T1** [comment]
Thank you for your excellent work. I am currently facing some issues. I want to reconstruct the data from the DNA-Rendering dataset using ENeRF, but I'm not sure how to configure the corresponding configuration file. Could you please provide me with some guidance?

**Comment by haotongl** [comment]
> Thank you for your excellent work. I am currently facing some issues. I want to reconstruct the data from the DNA-Rendering dataset using ENeRF, but I'm not sure how to configure the corresponding configuration file. Could you please provide me with some guidance?

Hi, thanks for your attention!
We include the enerf code for DNA-rendering (also called renbody dataset) in the following repo.
https://github.com/zju3dv/im4d/tree/main/configs/exps/enerf/renbody
