### ISSUE TITLE
Is there a GUI in this project?

### ISSUE THREAD

**Issue by ZCB-endeavor** [zju3dv/ENeRF#5]
Hi, thanks for your hard work. I'm trying to run ENeRF evaluate and it can work normally. I'm curious whether this project has a GUI to display the reconstruction model. Could you please tell me how to execute？

**Comment by haotongl** [comment]
We have released the GUI to display the reconstruction model. The ZJU-MoCap rendering demo in the project page is rendered by a model trained with 21 views. We will release this model soon. 

Until we open source this model, you can use the dtu_pretrain model instead.
