### ISSUE TITLE
weird result after visualizing on the ENeRF-Outdoor dataset 

### ISSUE THREAD

**Issue by deo651** [zju3dv/ENeRF#50]
Hi, thanks for your great work.
But when I inference on your ENeRF-Outdoor dataset, a weird result appears:
![image](https://github.com/zju3dv/ENeRF/assets/42883258/8ef0e8bf-0e48-427a-921a-aad939ba372c)
It doesn't make sense as the color is so gray. Could your please tell us why causes that?

**Comment by zhuangqirong** [comment]
> Hi, thanks for your great work. But when I inference on your ENeRF-Outdoor dataset, a weird result appears: ![image](https://user-images.githubusercontent.com/42883258/281949603-8ef0e8bf-0e48-427a-921a-aad939ba372c.png) It doesn't make sense as the color is so gray. Could your please tell us why causes that?

I also encountered this problem, how did you solve it?
