### ISSUE TITLE
Two questions regarding the video rendering accuracy and the number of inference cameras for Enerf Outdoor.

### ISSUE THREAD

**Issue by zhuangqirong** [zju3dv/ENeRF#53]
Thank you and your team for the great works you have made.
**1.Can the precision of the outdoor video, as presented on the Enerf homepage, be achieved by using the training, video rendering code, and outdoor dataset provided with the Enerf algorithm?**
 (I have conducted multiple training and testing sessions, increased the number of cameras from 4 to 8, and also increased the resolution. However, the obtained rendering results are only close to those of other users in the issues section, with a PSNR of around 27. There seems to be a noticeable gap in precision compared to the outdoor video presented on the homepage.)
**2.The outdoor rendering employs four camera positions for inference, but these four positions cannot be limited to just four, is that correct?**
 (After my testing, I found that to ensure precision, it is necessary to have eighteen camera positions and continually randomly select four positions for rendering. If only four fixed cameras are used, spaced 120 degrees apart, the results are particularly poor.)

Please verify if there are any issues with the description.

**Comment by haotongl** [comment]
Hi, thanks for your attention!
1. The released code should at least produce the results in the last reply of this issue:
https://github.com/zju3dv/ENeRF/issues/20. 

2. The outdoor rendering employs nearest 4 input cameras from 18 fixed cameras.
