### ISSUE TITLE
Is camera radial distortion taken into account?

### ISSUE THREAD

**Issue by roxanneluo** [zju3dv/ENeRF#54]
Hi,

Thanks for the great paper and sharing the codebase!

Some scenes like the LLFF ones have radial distortion in the camera parameters. Are radial distortion taken into account anyhow? For example, is there any undistorting the inputs, or somehow modeling radial distortion in constructing the rays?

Xuan

**Comment by haotongl** [comment]
Hi, thanks for your attention! The LLFF data provided by NeRF paper does not have any distortions.
For other datasets (e.g. ZJU-MoCap, ENeRF-Outdoor), the camera radial distortion are taken into account. The images are first undistorted, and then the rays and their corresponding RGB values are calculated to supervise ENeRF.
