### ISSUE TITLE
How to train on my own llff data?

### ISSUE THREAD

**Issue by HKCLynn** [zju3dv/ENeRF#9]
Thanks for your great work! I found that the README only writes how to train on the DTU dataset, but the [Depth_raw](https://virutalbuy-public.oss-cn-hangzhou.aliyuncs.com/share/cascade-stereo/CasMVSNet/dtu_data/dtu_train_hr/Depths_raw.zip) is difficult to get if I try to train my own llff data. What should I do? I would appreciate it if you could reply to me.

**Comment by haotongl** [comment]
Thank you for your attention. We provide an example config capable of training on LLFF format.
https://github.com/zju3dv/ENeRF/blob/master/configs/enerf/llff/fortress.yaml
